---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: omazzite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    snippets:
      - |
        # Remove KDE desktop packages to reduce image size
        # Use a simpler approach that doesn't rely on complex sed patterns
        dnf5 remove -y kde-settings kde-settings-pulseaudio kde-settings-minimal || true
        dnf5 remove -y plasma-workspace plasma-desktop plasma-systemsettings || true
        dnf5 remove -y kwin kwin-wayland kwin-x11 || true
        dnf5 remove -y kde-cli-tools kde-gtk-config || true
        # Remove any remaining KDE packages with wildcard
        dnf5 remove -y kde-settings* plasma* kwin* kde-cli* kde-gtk* || true
        # Clean DNF cache to reduce image size
        dnf5 clean all
        rm -rf /var/cache/dnf/*

  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
        - jdxcode/mise
        - atim/starship
        - scottames/ghostty
    install:
      # Disable weak dependencies to reduce image size and build time
      install-weak-deps: false
      packages:
        # Terminal and shell utilities
        - starship
        - alacritty
        - kitty
        - zoxide
        - ghostty

        # File managers and utilities
        - bat
        - du-dust
        - fd-find
        - fzf
        - ripgrep
        - tar
        - unzip
        - wget

        # Development tools
        - cargo
        - clang
        - dbus-devel
        - pkgconf-pkg-config
        - openssl-devel
        - libxcb-devel

        # Text editors and IDEs
        - neovim

        # System utilities
        - bind-utils
        - brightnessctl
        - btop
        - fastfetch
        - iputils
        - pciutils
        - plocate
        - tldr
        - usbutils
        - whois

        # Fonts
        - cascadia-code-nf-fonts
        - cascadia-mono-nf-fonts
        - fontawesome-fonts-all
        - google-noto-fonts-common

        # Applications
        - chromium
        - evince
        - gnome-calculator
        - gum
        - imv
        - mpv
        - nautilus

        # Input methods
        - fcitx5
        - fcitx5-configtool
        - fcitx5-gtk
        - fcitx5-qt

        # File system and networking
        - gvfs-mtp
        - gvfs-smb
        - iwd
        - pipx
        - playerctl

        # Hyprland ecosystem
        - hyprcursor
        - hypridle
        - hyprland
        - hyprland-qt-support
        - hyprland-qtutils
        - hyprlock
        - hyprpaper
        - hyprpicker
        - hyprpolkitagent
        - hyprshot
        - hyprsunset
        - hyprsysteminfo
        - hyprutils
        - hyprwayland-scanner

        # Desktop components
        - kvantum-qt5
        - mako
        - swaybg
        - uwsm
        - waybar
        - wf-recorder
        - wl-clipboard
        - wofi
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-hyprland
        - xdg-user-dirs

        # Theming and icons
        - gnome-themes-extra
        - xmlstarlet
        - yaru-icon-theme

        # Additional tools
        - mise
        - satty
        - slurp
        - sushi
        - curl
        - rsync
        - tmux
        - npm
        - meson
        - scdoc
        - pyprland
        - python3-pillow
        - python3-psutil
        - foot
        - jetbrains-mono-fonts
        - qt5ct
        - qt6ct
        - nwg-look
        - blueman
        - wdisplays
        - cliphist
        - gammastep
        - grimblast
        - pamixer
        - pavucontrol
        - swappy
        - swww
        - upower
        - yad
        - sddm

        # Boot and system
        - plymouth
        - plymouth-core-libs
        - plymouth-scripts
        - plymouth-system-theme
        - gnome-calculator
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - kitty
        - NetworkManager*
        - nwg-panel

  - type: script
    snippets:
      - |
        mkdir -p /etc/skel/.local/share/fonts
        fc-cache -f -v
  # Move omadora setup earlier to fail fast if there are issues
  - type: script
    snippets:
      - git clone https://github.com/elpritchos/omadora.git /etc/skel/.local/share/omadora

  - type: script
    snippets:
      - chmod +x /etc/skel/.local/share/omadora/bin/*

  - type: script
    snippets:
      - cargo install --root /etc/skel/.local/share/omadora bluetui cargo-update eza impala


  - type: script
    snippets:
      - mkdir -p "/etc/skel/.local/share/applications/icons"
      - cp /etc/skel/.local/share/omadora/applications/icons/*.png /etc/skel/.local/share/applications/icons/

  - type: script
    snippets:
      - /etc/skel/.local/share/omadora/bin/omadora-tui-install "Disk Usage" "bash -c 'dust -r; read -n 1 -s'" float "/etc/skel/.local/share/applications/icons/Disk Usage.png"
  - type: script
    snippets:
      - mkdir -p /etc/skel/.config
      - git clone https://github.com/LazyVim/starter /etc/skel/.config/nvim
      - cp -R /etc/skel/.local/share/omadora/config/nvim/* /etc/skel/.config/nvim/
      - rm -rf /etc/skel/.config/nvim/.git

  - type: script
    snippets:
      - sed -i 's/ --quiet//g' /etc/skel/.local/share/omadora/config/uwsm/env

  - type: script
    snippets:
      - cp -r /etc/skel/.local/share/omadora/config/* /etc/skel/.config/
      - mkdir -p /etc/fontconfig/conf.d && cp /etc/skel/.local/share/omadora/config/fontconfig/fonts.conf /etc/fontconfig/conf.d/99-omadora-fonts.conf
      - mkdir -p /etc/environment.d && cp /etc/skel/.local/share/omadora/config/environment.d/fcitx.conf /etc/environment.d/99-omadora-fcitx.conf
      - mkdir -p /usr/lib/systemd/user && cp -r /etc/skel/.local/share/omadora/config/systemd/user/* /usr/lib/systemd/user/
      - cp -r /etc/skel/.local/share/omadora/default/hypr/* /etc/skel/.config/hypr/
      - cp /etc/skel/.local/share/omadora/default/bashrc /etc/skel/.bashrc
      - cp /etc/skel/.local/share/omadora/default/xcompose /etc/skel/.XCompose
      - cp -r /etc/skel/.local/share/omadora/themes/* /usr/share/themes
      - mkdir -p /usr/share/icons/omadora && cp -r /etc/skel/.local/share/omadora/applications/icons/* /usr/share/icons/omadora/
      - mkdir -p /usr/share/plymouth/themes/sliced && cp -r /etc/skel/.local/share/omadora/default/plymouth/* /usr/share/plymouth/themes/sliced

  # - type: script
  #   snippets:
  #     - /etc/skel/.local/share/omadora/bin/plymouth-set-default-theme -R sliced

  - type: script
    snippets:
      - echo 'bind = SUPER, F4, exec, pavucontrol' >> /etc/skel/.config/hypr/bindings/media.conf

  - type: script
    snippets:
      - echo 'exec-once = sleep 5 && omadora-restart-waybar' >> /etc/skel/.config/hypr/autostart.conf

  - type: script
    snippets:
      - |
        # Create user-specific omadora setup (replicates omadora's user setup)
        mkdir -p /etc/skel/.config/omadora/themes
        mkdir -p /etc/skel/.config/omadora/current
        mkdir -p /etc/skel/.config/omadora/branding
        mkdir -p /etc/skel/.config/btop/themes
        mkdir -p /etc/skel/.config/mako
        mkdir -p /etc/skel/.config/nvim/lua/plugins

        # Copy branding files
        cp /etc/skel/.local/share/omadora/icon.txt /etc/skel/.config/omadora/branding/about.txt
        cp /etc/skel/.local/share/omadora/logo.txt /etc/skel/.config/omadora/branding/screensaver.txt

  - type: script
    snippets:
      - for theme in /usr/share/themes/*; do if [ -d "$theme" ]; then ln -nfs "$theme" /etc/skel/.config/omadora/themes/; fi; done

  - type: script
    snippets:
      - ln -snf /etc/skel/.config/omadora/themes/rose-pine-darker /etc/skel/.config/omadora/current/theme
      - ln -snf /etc/skel/.config/omadora/current/theme/backgrounds/01_background.png /etc/skel/.config/omadora/current/background

  - type: script
    snippets:
      - ln -snf /etc/skel/.config/omadora/current/theme/neovim.lua /etc/skel/.config/nvim/lua/plugins/theme.lua
      - ln -snf /etc/skel/.config/omadora/current/theme/btop.theme /etc/skel/.config/btop/themes/current.theme
      - ln -snf /etc/skel/.config/omadora/current/theme/mako.ini /etc/skel/.config/mako/config

  # Move flatpak setup earlier to catch issues sooner
  - type: script
    snippets:
      - echo -e "#!/bin/bash\nprofile=\"\$1\"\nif sudo tuned-adm profile \"\$profile\"; then\n    notify-send -a \"PowerProfiles\" \"Power profile set to '\$profile'\"\nelse\n    notify-send -a \"PowerProfiles\" \"Failed to set power profile to '\$profile'\"\n    exit 1\nfi" > /etc/skel/.local/share/omadora/bin/omadora-powerprofiles-set && chmod +x /etc/skel/.local/share/omadora/bin/omadora-powerprofiles-set
      - echo -e '#!/bin/bash\n# List available tuned profiles and format the output\ntuned-adm list | awk '\''/^Available profiles:/ {flag=1; next} /^Current active profile:/ {flag=0} flag && $1 !~ /^[[:space:]]*$/ {print $1}'\''' > /etc/skel/.local/share/omadora/bin/omadora-powerprofiles-list && chmod +x /etc/skel/.local/share/omadora/bin/omadora-powerprofiles-list

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  # Move xdg setup earlier - it's lightweight and has no dependencies
  - type: script
    snippets:
      - xdg-user-dirs-update

  # Move mimetypes setup earlier - lightweight configuration
  - type: script
    snippets:
      - |
        # Set default applications (mimetypes) - replicates omadora's mimetypes.sh
        xdg-mime default imv.desktop image/png image/jpeg image/gif image/webp image/bmp image/tiff
        xdg-mime default org.gnome.Evince.desktop application/pdf
        xdg-settings set default-web-browser chromium-browser.desktop
        xdg-mime default chromium-browser.desktop x-scheme-handler/http x-scheme-handler/https
        xdg-mime default mpv.desktop video/mp4 video/x-msvideo video/x-matroska video/x-flv video/x-ms-wmv video/mpeg video/ogg video/webm video/quicktime video/3gpp video/3gpp2 video/x-ms-asf video/x-ogm+ogg video/x-theora+ogg application/ogg

  - type: script
    snippets:
      - dnf remove -y "@gnome-desktop" || true
      - dnf remove -y "@gnome-apps" || true
      - dnf remove -y "@kde-desktop" || true
      - dnf remove -y "@kde-plasma" || true
      - dnf install -y "@development-tools" || true
      - dnf install -y "@development-libs" || true
      - dnf install -y "@fonts" || true
      - dnf install -y "@hardware-support" || true
      - dnf install -y "@multimedia" || true
      - dnf group remove -y networkmanager-submodules || true

  - type: script
    snippets:
      - gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
      - gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
      - gsettings set org.gnome.desktop.interface icon-theme "Yaru-blue"
      - ln -snf /usr/share/icons/Adwaita/symbolic/actions/go-previous-symbolic.svg /usr/share/icons/Yaru/scalable/actions/go-previous-symbolic.svg
      - ln -snf /usr/share/icons/Adwaita/symbolic/actions/go-next-symbolic.svg /usr/share/icons/Yaru/scalable/actions/go-next-symbolic.svg
      - gtk-update-icon-cache /usr/share/icons/Yaru
      - pipx install terminaltexteffects

  # Cargo tools are compiled after omadora setup

  - type: script
    snippets:
      - cargo install --root /etc/skel/.local/share/omadora bluetui cargo-update eza impala
      - fc-cache -f -v
      - mkdir -p /var/lib/plocate && updatedb
      - rm -rf /etc/NetworkManager

  - type: script
    snippets:
      - systemctl set-default graphical.target

  - type: script
    snippets:
      - rm -rf /etc/NetworkManager

  # Updatedb is optional and may fail if plocate database isn't initialized yet

  - type: script
    snippets:
      - |
        # Set up GPG configuration (replicates omadora's gpg.sh)
        mkdir -p /etc/gnupg
        cp /etc/skel/.local/share/omadora/default/gpg/dirmngr.conf /etc/gnupg/
        chmod 644 /etc/gnupg/dirmngr.conf

      - |
        # Fix DHCP DNS to allow VPN DNS override (from migration 1757481073.sh)
        if [ -f /etc/systemd/resolved.conf ]; then if grep -q "^DNS=$" /etc/systemd/resolved.conf && grep -q "^FallbackDNS=$" /etc/systemd/resolved.conf; then sed -i '/^DNS=$/d; /^FallbackDNS=$/d' /etc/systemd/resolved.conf && systemctl restart systemd-resolved || true; fi; fi
      - |
        # Fix Nautilus navigation icons (from migration 1756609102.sh)
        ln -snf /usr/share/icons/Adwaita/symbolic/actions/go-previous-symbolic.svg /usr/share/icons/Yaru/scalable/actions/go-previous-symbolic.svg
        ln -snf /usr/share/icons/Adwaita/symbolic/actions/go-next-symbolic.svg /usr/share/icons/Yaru/scalable/actions/go-next-symbolic.svg
        gtk-update-icon-cache /usr/share/icons/Yaru

  - type: systemd
    system:
      enabled:
        - systemd-networkd.service
        - iwd.service
        - sddm.service
      disabled:
        - systemd-networkd-wait-online.service
      masked:
        - systemd-networkd-wait-online.service
    user:
      enabled:
        - omadora-battery-monitor.service
        - omadora-battery-monitor.timer

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
